export const techno = [
	{ src: 'banner/react.svg', link: 'https://reactjs.org/' },
	{
		src: 'banner/typescript.png',
		link: 'https://www.typescriptlang.org/',
	},
	{ src: 'banner/tailwind.png', link: 'https://tailwindcss.com/' },
	{ src: 'banner/python.png', link: 'https://www.python.org/' },
	{ src: 'banner/fastapi.png', link: 'https://fastapi.tiangolo.com/' },
	{ src: 'banner/nodejs.svg', link: 'https://nodejs.org/en/' },
];

export const tools = [
	{ src: 'banner/vscode.png', link: 'https://code.visualstudio.com/' },
	{ src: 'banner/git.png', link: 'https://git-scm.com/' },
	{ src: 'banner/postman.png', link: 'https://www.postman.com/' },
	{ src: 'banner/termius.png', link: 'https://termius.com/' },
	{ src: 'banner/copilot.png', link: 'https://copilot.github.com/' },
	{ src: 'banner/openai.png', link: 'https://openai.com/' },
	{ src: 'banner/figma.png', link: 'https://www.figma.com/' },
	{ src: 'banner/photoshop.png', link: 'https://www.adobe.com/' },
]

export const projects = [
	{
		name: 'OMG',
		description:
			'OddMailGuard is a website that allows users to transfer an email to the given address and assign an oddness score to it. It analyzes the sender, subject, body and attachments to determine the oddness of the email.',
		type: 'Web',
		technologies: [
			'React',
			'TypeScript',
			'TailwindCSS',
			'Framer Motion',
			'FastAPI',
			'Python',
			'IMAP',
		],
		link: 'https://omg.elwan.ch/',
		github: 'https://github.com/YungBricoCoop/omg',
		image: 'gradients/gradient1.jpg',
	},
	{
		name: 'Portfolio V3',
		description:
			'A sleek and minimalistic third version of my personal portfolio, showcasing my work while maintaining a visually appealing design.',
		type: 'Web',
		technologies: [
			'React',
			'TypeScript',
			'TailwindCSS',
			'Framer Motion',
			'Spline',
			'ThreeJS',
		],
		link: 'https://elwan.ch/',
		github: 'https://github.com/YungBricoCoop/portfolio',
		image: 'gradients/gradient8.jpg',
	},
	{
		name: 'ELMA',
		description:
			'ELMA is a comprehensive private solution for managing clients, invoices, and services. It streamlines tracking work done for each client, generating invoices, and handling payments.',
		type: 'Fullstack',
		technologies: [
			'React',
			'TypeScript',
			'TailwindCSS',
			'MySQL',
			'FastAPI',
			'Python',
			'Nginx',
		],
		image: 'gradients/gradient2.jpg',
	},
	{
		name: 'Sophy Dashboard',
		description:
			'A private dashboard project designed to manage job applications, track their progress, and assess the relevance of each application',

		type: 'Fullstack',
		technologies: [
			'React',
			'TailwindCSS',
			'FileMaker',
			'Flask',
			'Python',
			'Nginx',
		],
		image: 'gradients/gradient5.jpg',
	},
	{
		name: 'Resume Dyno',
		description:
			'A Chrome extension leveraging ChatGPT to extract resume data and return it in a customizable JSON format. Settings allow for adjustments to the JSON structure.',
		type: 'Extension',
		technologies: ['React', 'TypeScript', 'TailwindCSS', 'Rollup', 'ChatGPT', 'FastAPI'],
		github: 'https://github.com/YungBricoCoop/resume-dyno',
		image: 'gradients/gradient6.jpg',
	},
	{
		name: 'Vite React Starter',
		description:
			'A TypeScript React project starter template, built on Vite, featuring TailwindCSS, React Router, and Prettier integration.',
		type: 'Boilerplate',
		technologies: ['React', 'TypeScript', 'TailwindCSS', 'Vite'],
		github: 'https://github.com/YungBricoCoop/vite-react-starter',
		image: 'gradients/gradient3.jpg',
	},
	{
		name: 'Blastify',
		description:
			'A user-friendly web app showcasing your top Spotify artists, tracks, and albums. Inspired by the macOS Monterey design, Blastify delivers an engaging interface.',
		type: 'Web',
		technologies: ['React', 'TailwindCSS', 'Spotify API'],
		link: 'https://elwan.ch/blastify',
		github: 'https://github.com/YungBricoCoop/blastify',
		image: 'gradients/gradient5.jpg',
	},
	{
		name: 'Wombo AI Scraper',
		description:
			'A scraping tool developed to download images generated by the Wombo AI app. Utilizes Selenium to interact with the website and download images. Currently has 17⭐ on GitHub.',
		type: 'Script',
		technologies: ['Python', 'Selenium'],
		github: 'https://github.com/YungBricoCoop/wombo-ai-scraper',
		image: 'gradients/gradient8.jpg',
	}
]